# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Email')),
                ('pri_nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('ult_nome', models.CharField(max_length=200, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF (opcional)')),
                ('dt_nasc', models.DateTimeField(null=True, verbose_name='Data Nascimento')),
                ('idFirebase', models.CharField(blank=True, max_length=200, null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
