# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cofferBackend', '0002_carteira_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='lancamento',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.CharField(max_length=400, primary_key=True, serialize=False, verbose_name='Descrição do Lançamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data do Vencimento')),
                ('ref_pgto_atual', models.IntegerField(default=1, verbose_name='Parcela Atual')),
                ('ref_pgto_total', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('flg_mandatorio', models.BooleanField(default=False, verbose_name='Pagamento Obrigatório')),
                ('cod_barras', models.CharField(max_length=400, null=True, verbose_name='Descrição do Lançamento')),
                ('cpf_cnpj_cedente', models.IntegerField(null=True, verbose_name='CPF/CNPJ do Cedente')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data do Pagamento Efetuado')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor Efetuado')),
                ('efetuado', models.CharField(choices=[('Pgo', 'Pago'), ('Pend', 'Pendente'), ('Canc', 'Cancelado'), ('Adia', 'Adiado')], default='Pend', max_length=10, verbose_name='Status Pagamento')),
                ('tags', models.CharField(max_length=500, null=True, verbose_name='#Tags')),
                ('tipo_despesa', models.CharField(choices=[('fixo', 'Fixo'), ('var', 'Variável')], default='var', max_length=10, null=True, verbose_name='Tipo Despesa')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cofferBackend.Usuario')),
                ('des_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cofferBackend.Categoria')),
                ('nm_carteira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cofferBackend.Carteira')),
            ],
        ),
    ]
