# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-20 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cofferBackend', '0003_lancamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lancamento',
            new_name='Lancamentooo',
        ),
    ]
