# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofferBackend', '0006_auto_20180920_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pri_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ult_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sobrenome'),
        ),
    ]
